<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>Facturacion.WPF.Client</RootNamespace>
    <AssemblyName>Facturacion.WPF.Client</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>

</Project>